server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761/eureka}

management:
  security:
    enabled: false

spring:
  application:
    name: lunar-calendar
  profiles:
    active: local
    #active: deploy
  mvc:
    format:
      date-time: "yyyy-MM-dd HH:mm:ss"
  data:
    web:
      pageable:
        max-page-size: 50
logging:
  config: classpath:logback-spring.xml
  level:
    com:
      codism: info
    root: error
    org:
      hibernate:
        SQL: debug
