cloud:
  gateway:
    uri: ${LOCAL_URL:http://localhost:8080}
  fe:
    uri: ${FE_URL:http://localhost:3000}
spring:
  cloud:
    service-registry:
      auto-registration:
        enabled: 'false'
  datasource:
    url: jdbc:postgresql://localhost:5433/lunar_calendar
    username: postgres
    password: q1w2e3r4!!
    driver-class-name: org.postgresql.Driver